---
galaxy_info:
  role_name: podman_clean
  author: workshop-lab
  description: Removes easyTravel application containers/network and image using Podman
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "9"

dependencies: []
