manifestVersion: 1.0
projects:
  - name: destination-automation
    path: destination-automation
environmentGroups:
  - name: destination-automation-environment-group
    environments:
      - name: destination-automation-environment
        url:
          type: environment
          value: DT_PLATFORM_URL
        auth:
          platformToken:
            type: environment
            name: DT_PLATFORM_TOKEN
