---
galaxy_info:
  author: "destination-automation"
  description: "Remediates AI embedding model to the correct value via the app OpenFeature API"
  company: "Red Hat"
  license: "MIT"
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "9"

dependencies: []
